# Generated by Django 4.2.6 on 2023-11-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_orderedtokens_order_number_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("PayPal", "PayPal"), ("Mpesa", "Mpesa")],
                default="Mpesa",
                max_length=100,
            ),
        ),
    ]
