# Generated by Django 4.2.6 on 2023-11-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
