# Generated by Django 4.2.6 on 2023-11-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_order_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="room_number",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="1000600237", max_length=10, unique=True),
        ),
    ]
