# Generated by Django 4.2.6 on 2023-11-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="100238157", max_length=10, unique=True),
        ),
    ]
